url_stp="panel/stp/"
url_route="panel/routing/"
url_etherchannel="panel/etherchannel/"
url_settings="panel/settings/"
url_panel="panel/"
url_dynamicarp="panel/dynamicarp/"
url_portsecurity="panel/portsecurity/"
#url_stp="/panel/stp"
